apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  type: NodePort
  selector:
    app: my-deploy
  ports:
    - port: 8007           # exposed port
      targetPort: 8000     # container port
      # nodePort: auto-assigned by Kubernetes
